query getWarehouse($id: Int!) {
  warehouse(id: $id) {
    warehouseId
    warehouseName
    warehouseCode
    address
    manager
    region
    status
    totalProducts
    availableSectors
    capacityUtilization
  }
}
