query GetInventoryDashboard {
  inventoryItems {
    id
    itemSKU
    productName
    category
    warehouseLocation
    rackLocation
    quantityInStock
    reorderLevel
    unitOfMeasure
    costPerUnit
    totalValue
    lastRestocked
  }
  totalInventoryValue
  inStockItems
  lowStockItems
  outOfStockItems
}
