query SearchByCategory($category: String!) {
  itemByCategory(category: $category) {
    id
    itemSKU
    productName
    category
    warehouseLocation
    rackLocation
    quantityInStock
    reorderLevel
    unitOfMeasure
    costPerUnit
    totalValue
    lastRestocked
  }
}
