query GetItemByWarehouseLocation($warehouseName: String!) {
  itemByWarehouseLocation(warehouseName: $warehouseName) {
    id
    itemSKU
    productName
    category
    warehouseLocation
    rackLocation
    quantityInStock
    reorderLevel
    unitOfMeasure
    costPerUnit
    totalValue
    lastRestocked
  }
}
