query GetStorageLocationWarehouse($warehouseName: String!) {
  storageLocationWarehouse(warehouseName: $warehouseName) {
    id
    locationCode
    maxCapacity
    occupiedCapacity
    unitType
    storageType
    sectionName
    createdAt
    warehouse {
      id
      warehouseName
      warehouseCode
    }
    user {
      id
      firstName
      lastName
      email
    }
  }
}
